// ═══════════════════════════════════════════════════════════════════════════════
// HamadaOS — Generated Colors (matugen output)
// ═══════════════════════════════════════════════════════════════════════════════
// THIS FILE IS AUTO-GENERATED BY MATUGEN. DO NOT EDIT MANUALLY.
//
// matugen reads the current wallpaper, extracts a Material Design 3
// tonal palette, and writes this file. Theme.qml imports this singleton
// so every QML component updates in the same frame.
//
// Defaults are Catppuccin Mocha — they work immediately before the first
// wallpaper is set.
//
// Reference:
//   ilyamiro/imperative-dots — MatugenColors.qml (Process + JSON pattern)
//   end-4/dots-hyprland      — m3colors in Appearance.qml
// ═══════════════════════════════════════════════════════════════════════════════

pragma Singleton
import QtQuick

QtObject {
    // ── Primary palette ───────────────────────────────────────────────────
    property color primary:        "#cba6f7"   // Mauve
    property color onPrimary:      "#1e1e2e"   // Crust (text on primary)

    // ── Surface hierarchy ──────────────────────────────────────────────────
    property color surface:        "#1e1e2e"   // Crust (deepest background)
    property color surfaceVariant: "#313244"   // Surface0 (cards, sheets)
    property color onSurface:      "#cdd6f4"   // Text (primary content)
    property color onSurfaceVar:   "#a6adc8"   // Subtext0 (secondary content)

    // ── Outline ────────────────────────────────────────────────────────────
    property color outline:        "#585b70"   // Surface2 (borders, dividers)

    // ── Error ──────────────────────────────────────────────────────────────
    property color error:          "#f38ba8"   // Red

    // ── Extended palette ──────────────────────────────────────────────────
    property color secondary:      "#89b4fa"   // Blue
    property color tertiary:       "#94e2d5"   // Teal
    property color surfaceBright:  "#45475a"   // Surface1
    property color surfaceDim:     "#181825"   // Mantle
    property color shadow:         "#11111b"   // Base (darkest)
    property color scrim:          "#000000"   // Pure black for overlays

    // ── Terminal palette (for kitty, foot, etc.) ──────────────────────────
    property color termBlack:      "#45475a"
    property color termRed:        "#f38ba8"
    property color termGreen:      "#a6e3a1"
    property color termYellow:     "#f9e2af"
    property color termBlue:       "#89b4fa"
    property color termMagenta:    "#f5c2e7"
    property color termCyan:       "#94e2d5"
    property color termWhite:      "#bac2de"
}
