// ═══════════════════════════════════════════════════════════════════════════════
// HamadaOS — Animation Service
// ═══════════════════════════════════════════════════════════════════════════════
// Drives Settings → Animations. Writes the HamadaOS animation preset into
// HyDE's animation system the HyDE-native way:
//
//   ~/.config/hypr/animations/hamadaos.conf   ← we own this preset file
//   ~/.config/hypr/animations.conf            ← HyDE pointer ($ANIMATION=hamadaos)
//
// Files are written with FileView.setText (atomic, no shell quoting games),
// then `hyprctl reload` hot-reloads the compositor.
//
// QML-side durations follow automatically: Theme.duration* divide by
// Config.options.animationSpeed, so shell and compositor stay in step.
// ═══════════════════════════════════════════════════════════════════════════════

pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import qs.modules.common

Singleton {
    id: root

    readonly property string presetPath:
        Quickshell.env("HOME") + "/.config/hypr/animations/hamadaos.conf"
    readonly property string pointerPath:
        Quickshell.env("HOME") + "/.config/hypr/animations.conf"

    // ── Preset → curve mapping ───────────────────────────────────────────────
    property var presets: ({
        "iOS Spring": {
            windowsIn: "iosSpring", windowsOut: "macosClose",
            windowsMove: "fluentSnap", workspaces: "macosSpace", layers: "iosSpring",
            description: "Bouncy spring physics — windows breathe in, settle smoothly"
        },
        "macOS Elastic": {
            windowsIn: "macosOpen", windowsOut: "macosClose",
            windowsMove: "macosSpace", workspaces: "macosSpace", layers: "macosOpen",
            description: "macOS Sonoma feel — elastic deceleration, tiny overshoot"
        },
        "Windows Fluent": {
            windowsIn: "fluentSnap", windowsOut: "fluidExit",
            windowsMove: "fluentSnap", workspaces: "fluentSnap", layers: "fluentSnap",
            description: "Windows 11 Fluent — snap-in, soft tail, zero bounce"
        },
        "Instant": {
            windowsIn: "macosClose", windowsOut: "fluidExit",
            windowsMove: "fluentSnap", workspaces: "fluentSnap", layers: "fluidExit",
            description: "Minimal motion — everything lands immediately"
        }
    })

    property var beziers: ({
        macosOpen:  "0.05, 0.9,  0.1,  1.05",
        macosClose: "0.4,  0.0,  1.0,  1.0",
        macosSpace: "0.25, 0.46, 0.45, 0.94",
        iosSpring:  "0.34, 1.56, 0.64, 1.0",
        fluentSnap: "0.0,  0.9,  0.58, 1.0",
        fluidExit:  "0.6,  0.05, 0.95, 0.05"
    })

    function setSpeed(multiplier) {
        Config.options.animationSpeed = multiplier
        apply()
    }

    function applyPreset(name) {
        if (!presets[name]) return
        Config.options.animationPreset = name
        apply()
    }

    function setEnabled(enabled) {
        Config.options.animations = enabled
        apply()
    }

    function apply() {
        const speed = Math.max(0.25, Config.options.animationSpeed)
        const p = presets[Config.options.animationPreset] ?? presets["iOS Spring"]
        const c = beziers
        const d = base => Math.max(1, Math.round(base / speed))

        presetFile.setText(
`# ═══════════════════════════════════════════════════════════
# HamadaOS — Animations (auto-generated by AnimationService)
# Preset: ${Config.options.animationPreset}  |  Speed: ${Config.options.animationSpeed}x
# Edit from Settings → Animations, not here.
# ═══════════════════════════════════════════════════════════

animations {
    enabled = ${Config.options.animations ? "yes" : "no"}
    first_launch_animation = true

    bezier = macosOpen,  ${c.macosOpen}
    bezier = macosClose, ${c.macosClose}
    bezier = macosSpace, ${c.macosSpace}
    bezier = iosSpring,  ${c.iosSpring}
    bezier = fluentSnap, ${c.fluentSnap}
    bezier = fluidExit,  ${c.fluidExit}

    animation = windowsIn,   1, ${d(3)}, ${p.windowsIn},   popin 80%
    animation = windowsOut,  1, ${d(2)}, ${p.windowsOut},  popin 90%
    animation = windowsMove, 1, ${d(3)}, ${p.windowsMove}, slide

    animation = workspaces,       1, ${d(3)}, ${p.workspaces}, slide
    animation = specialWorkspace, 1, ${d(3)}, macosOpen, slidevert

    animation = layersIn,  1, ${d(3)}, ${p.layers},  popin 93%
    animation = layersOut, 1, ${d(2)}, fluidExit, fade

    animation = fadeIn,        1, ${d(3)}, macosOpen
    animation = fadeOut,       1, ${d(2)}, fluidExit
    animation = fadeLayersIn,  1, ${d(3)}, macosOpen
    animation = fadeLayersOut, 1, ${d(2)}, fluidExit
    animation = fadeDim,       1, ${d(3)}, macosSpace
    animation = fadeShadow,    1, ${d(3)}, macosSpace

    animation = border, 1, 10, macosSpace
}
`)

        pointerFile.setText(
`# HamadaOS owns the animation selection. To go back to a HyDE preset,
# run: animations.sh --select
$ANIMATION=hamadaos
$ANIMATION_PATH=./animations/hamadaos.conf
source = $ANIMATION_PATH
`)

        reloadTimer.restart()
    }

    // Give both writes a moment to land before reloading the compositor.
    Timer {
        id: reloadTimer
        interval: 150; repeat: false
        onTriggered: Quickshell.execDetached(["hyprctl", "reload"])
    }

    FileView { id: presetFile;  path: root.presetPath }
    FileView { id: pointerFile; path: root.pointerPath }
}
