#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# HamadaOS — Gaming Mode Toggle
# ═══════════════════════════════════════════════════════════════════════════════
# Single source of truth. Triggered three ways:
#   · Super+Shift+G
#   · Settings → Gaming toggle (Quickshell watches the flag file)
#   · AUTOMATICALLY by GameMode hooks when any game starts/stops (gamemode.ini)
#
# ON:
#   · HyDE "gaming" workflow      (blur/shadows/animations off → GPU freed)
#   · tuned throughput-performance + hamadaos-perf-tune gaming
#       (governor, THP=always, MGLRU min_ttl — the anti-8fps-drop fix,
#        PCIe ASPM off, NVIDIA persistence)
#   · sched_ext → scx_lavd        (latency-criticality scheduler, built for
#                                  gaming on weak/handheld hardware)
#   · VRR fullscreen-only
#   · TDP-shared thin laptops + "GPU priority" setting → CPU boost capped
#     so the package watts flow to the GPU instead
#
# All privileged calls go through the fixed-args sudoers whitelist.
# ═══════════════════════════════════════════════════════════════════════════════

set -uo pipefail

FLAG_FILE="${XDG_RUNTIME_DIR:-/tmp}/hamadaos-gaming-mode"
CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/hamadaos"

# Hardware profile (generated by hamadaos-hw-profile.sh)
TDP_SHARED=0; IS_LAPTOP=0
# shellcheck disable=SC1091
[[ -f "$CFG_DIR/hardware.env" ]] && source "$CFG_DIR/hardware.env"

# User settings
GPU_PRIORITY="false"
if command -v jq >/dev/null 2>&1 && [[ -f "$CFG_DIR/config.json" ]]; then
    GPU_PRIORITY="$(jq -r '.gpuPriority // false' "$CFG_DIR/config.json" 2>/dev/null)"
fi

notify() {
    notify-send -a "HamadaOS" -i "input-gaming" -t 3000 "$1" "$2" 2>/dev/null || true
}

set_workflow() {
    hyde-shell workflows.sh select "$1" >/dev/null 2>&1 \
        || hyde-shell workflows --select "$1" >/dev/null 2>&1 || true
}

set_scheduler() {  # $1 = lavd | default   (sched_ext, CachyOS scx_loader)
    if command -v scxctl >/dev/null 2>&1; then
        if [[ "$1" == "lavd" ]]; then
            scxctl start --sched scx_lavd --mode gaming >/dev/null 2>&1 \
                || scxctl switch --sched scx_lavd >/dev/null 2>&1 || true
        else
            scxctl stop >/dev/null 2>&1 || true
        fi
    fi
}

if [[ -f "$FLAG_FILE" ]]; then
    # ── DISABLE ────────────────────────────────────────────────────────────────
    pkill -f hamadaos-thermal-guard 2>/dev/null || true
    balooctl6 resume 2>/dev/null || balooctl resume 2>/dev/null || true
    sudo -n tuned-adm profile balanced 2>/dev/null || true
    sudo -n /usr/local/bin/hamadaos-perf-tune balanced 2>/dev/null || true
    sudo -n /usr/local/bin/hamadaos-perf-tune cpu-boost-on 2>/dev/null || true
    set_scheduler default
    hyprctl keyword misc:vrr 1 >/dev/null 2>&1 || true
    set_workflow default
    rm -f "$FLAG_FILE"
    notify "Gaming Mode OFF" "Balanced profile · effects restored"
else
    # ── ENABLE ─────────────────────────────────────────────────────────────────
    # On battery, performance mode mostly produces heat — warn but proceed.
    if [[ "$IS_LAPTOP" == "1" ]] && ! on_ac_power 2>/dev/null; then
        notify "On battery" "Gaming mode works best plugged in"
    fi

    sudo -n tuned-adm profile throughput-performance 2>/dev/null || true
    sudo -n /usr/local/bin/hamadaos-perf-tune gaming 2>/dev/null || true
    set_scheduler lavd
    hyprctl keyword misc:vrr 2 >/dev/null 2>&1 || true
    # Direct scanout: fullscreen game buffer goes straight to the display
    # engine, skipping a composition pass — on MUX-less hybrids this removes
    # one PCIe copy per frame. (Falls back silently on older Hyprland.)
    hyprctl keyword render:direct_scanout 1 >/dev/null 2>&1 \
        || hyprctl keyword misc:no_direct_scanout 0 >/dev/null 2>&1 || true
    set_workflow gaming

    # The counterintuitive thin-laptop win: cap CPU boost → GPU gets the watts.
    if [[ "$TDP_SHARED" == "1" && "$GPU_PRIORITY" == "true" ]]; then
        sudo -n /usr/local/bin/hamadaos-perf-tune cpu-boost-off 2>/dev/null || true
        EXTRA=" · CPU boost capped (GPU priority)"
    else
        EXTRA=""
    fi

    # File indexer steals random I/O + CPU exactly when games stream assets.
    balooctl6 suspend 2>/dev/null || balooctl suspend 2>/dev/null || true

    # Thermal guard: hysteresis stepper, laptops only (exits instantly on desktops)
    pgrep -f hamadaos-thermal-guard >/dev/null 2>&1 \
        || nohup "$HOME/.config/hypr/scripts/hamadaos-thermal-guard.sh" >/dev/null 2>&1 &

    touch "$FLAG_FILE"
    notify "Gaming Mode ON" "scx_lavd · THP · MGLRU lock · effects off${EXTRA}"
fi
